// Code generated by entc, DO NOT EDIT.

package positionassingment

const (
	// Label holds the string label denoting the positionassingment type in the database.
	Label = "positionassingment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDayStart holds the string denoting the daystart field in the database.
	FieldDayStart = "day_start"

	// EdgeFormdata holds the string denoting the formdata edge name in mutations.
	EdgeFormdata = "formdata"
	// EdgeFormdepartment holds the string denoting the formdepartment edge name in mutations.
	EdgeFormdepartment = "formdepartment"
	// EdgeFormposition holds the string denoting the formposition edge name in mutations.
	EdgeFormposition = "formposition"

	// Table holds the table name of the positionassingment in the database.
	Table = "positionassingments"
	// FormdataTable is the table the holds the formdata relation/edge.
	FormdataTable = "positionassingments"
	// FormdataInverseTable is the table name for the Physician entity.
	// It exists in this package in order to avoid circular dependency with the "physician" package.
	FormdataInverseTable = "physicians"
	// FormdataColumn is the table column denoting the formdata relation/edge.
	FormdataColumn = "physician_user"
	// FormdepartmentTable is the table the holds the formdepartment relation/edge.
	FormdepartmentTable = "positionassingments"
	// FormdepartmentInverseTable is the table name for the Department entity.
	// It exists in this package in order to avoid circular dependency with the "department" package.
	FormdepartmentInverseTable = "departments"
	// FormdepartmentColumn is the table column denoting the formdepartment relation/edge.
	FormdepartmentColumn = "department_department"
	// FormpositionTable is the table the holds the formposition relation/edge.
	FormpositionTable = "positionassingments"
	// FormpositionInverseTable is the table name for the Position entity.
	// It exists in this package in order to avoid circular dependency with the "position" package.
	FormpositionInverseTable = "positions"
	// FormpositionColumn is the table column denoting the formposition relation/edge.
	FormpositionColumn = "position_position"
)

// Columns holds all SQL columns for positionassingment fields.
var Columns = []string{
	FieldID,
	FieldDayStart,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Positionassingment type.
var ForeignKeys = []string{
	"department_department",
	"physician_user",
	"position_position",
}
