// Code generated by entc, DO NOT EDIT.

package positionassingment

const (
	// Label holds the string label denoting the positionassingment type in the database.
	Label = "positionassingment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDayStart holds the string denoting the daystart field in the database.
	FieldDayStart = "day_start"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"

	// Table holds the table name of the positionassingment in the database.
	Table = "positionassingments"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "positionassingments"
	// UserInverseTable is the table name for the Physician entity.
	// It exists in this package in order to avoid circular dependency with the "physician" package.
	UserInverseTable = "physicians"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "physician_formuser"
	// DepartmentTable is the table the holds the department relation/edge.
	DepartmentTable = "positionassingments"
	// DepartmentInverseTable is the table name for the Department entity.
	// It exists in this package in order to avoid circular dependency with the "department" package.
	DepartmentInverseTable = "departments"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_formdepartment"
	// PositionTable is the table the holds the position relation/edge.
	PositionTable = "positionassingments"
	// PositionInverseTable is the table name for the Position entity.
	// It exists in this package in order to avoid circular dependency with the "position" package.
	PositionInverseTable = "positions"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "position_formposition"
)

// Columns holds all SQL columns for positionassingment fields.
var Columns = []string{
	FieldID,
	FieldDayStart,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Positionassingment type.
var ForeignKeys = []string{
	"department_formdepartment",
	"physician_formuser",
	"position_formposition",
}
