// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Physician is the predicate function for physician builders.
type Physician func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Positionassingment is the predicate function for positionassingment builders.
type Positionassingment func(*sql.Selector)
