// Code generated by entc, DO NOT EDIT.

package department

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartmentname holds the string denoting the departmentname field in the database.
	FieldDepartmentname = "departmentname"

	// EdgeFormdepartment holds the string denoting the formdepartment edge name in mutations.
	EdgeFormdepartment = "formdepartment"

	// Table holds the table name of the department in the database.
	Table = "departments"
	// FormdepartmentTable is the table the holds the formdepartment relation/edge.
	FormdepartmentTable = "positionassingments"
	// FormdepartmentInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	FormdepartmentInverseTable = "positionassingments"
	// FormdepartmentColumn is the table column denoting the formdepartment relation/edge.
	FormdepartmentColumn = "department_formdepartment"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDepartmentname,
}
