// Code generated by entc, DO NOT EDIT.

package department

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartmentname holds the string denoting the departmentname field in the database.
	FieldDepartmentname = "departmentname"

	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"

	// Table holds the table name of the department in the database.
	Table = "departments"
	// DepartmentTable is the table the holds the department relation/edge.
	DepartmentTable = "positionassingments"
	// DepartmentInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	DepartmentInverseTable = "positionassingments"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_department"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDepartmentname,
}
