// Code generated by entc, DO NOT EDIT.

package position

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameposition holds the string denoting the nameposition field in the database.
	FieldNameposition = "nameposition"

	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"

	// Table holds the table name of the position in the database.
	Table = "positions"
	// PositionTable is the table the holds the position relation/edge.
	PositionTable = "positionassingments"
	// PositionInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	PositionInverseTable = "positionassingments"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "position_position"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldNameposition,
}
