// Code generated by entc, DO NOT EDIT.

package position

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameposition holds the string denoting the nameposition field in the database.
	FieldNameposition = "nameposition"

	// EdgeFormposition holds the string denoting the formposition edge name in mutations.
	EdgeFormposition = "formposition"

	// Table holds the table name of the position in the database.
	Table = "positions"
	// FormpositionTable is the table the holds the formposition relation/edge.
	FormpositionTable = "positionassingments"
	// FormpositionInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	FormpositionInverseTable = "positionassingments"
	// FormpositionColumn is the table column denoting the formposition relation/edge.
	FormpositionColumn = "POSITION_ID"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldNameposition,
}
