// Code generated by entc, DO NOT EDIT.

package position

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/konrawitAEK/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Nameposition applies equality check predicate on the "Nameposition" field. It's identical to NamepositionEQ.
func Nameposition(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameposition), v))
	})
}

// NamepositionEQ applies the EQ predicate on the "Nameposition" field.
func NamepositionEQ(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameposition), v))
	})
}

// NamepositionNEQ applies the NEQ predicate on the "Nameposition" field.
func NamepositionNEQ(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNameposition), v))
	})
}

// NamepositionIn applies the In predicate on the "Nameposition" field.
func NamepositionIn(vs ...string) predicate.Position {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Position(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNameposition), v...))
	})
}

// NamepositionNotIn applies the NotIn predicate on the "Nameposition" field.
func NamepositionNotIn(vs ...string) predicate.Position {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Position(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNameposition), v...))
	})
}

// NamepositionGT applies the GT predicate on the "Nameposition" field.
func NamepositionGT(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNameposition), v))
	})
}

// NamepositionGTE applies the GTE predicate on the "Nameposition" field.
func NamepositionGTE(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNameposition), v))
	})
}

// NamepositionLT applies the LT predicate on the "Nameposition" field.
func NamepositionLT(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNameposition), v))
	})
}

// NamepositionLTE applies the LTE predicate on the "Nameposition" field.
func NamepositionLTE(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNameposition), v))
	})
}

// NamepositionContains applies the Contains predicate on the "Nameposition" field.
func NamepositionContains(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNameposition), v))
	})
}

// NamepositionHasPrefix applies the HasPrefix predicate on the "Nameposition" field.
func NamepositionHasPrefix(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNameposition), v))
	})
}

// NamepositionHasSuffix applies the HasSuffix predicate on the "Nameposition" field.
func NamepositionHasSuffix(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNameposition), v))
	})
}

// NamepositionEqualFold applies the EqualFold predicate on the "Nameposition" field.
func NamepositionEqualFold(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNameposition), v))
	})
}

// NamepositionContainsFold applies the ContainsFold predicate on the "Nameposition" field.
func NamepositionContainsFold(v string) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNameposition), v))
	})
}

// HasPosition applies the HasEdge predicate on the "position" edge.
func HasPosition() predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PositionTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PositionTable, PositionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionWith applies the HasEdge predicate on the "position" edge with a given conditions (other predicates).
func HasPositionWith(preds ...predicate.Positionassingment) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PositionInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PositionTable, PositionColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		p(s.Not())
	})
}
