// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/konrawitAEK/app/ent/physician"
	"github.com/konrawitAEK/app/ent/positionassingment"
	"github.com/konrawitAEK/app/ent/predicate"
)

// PhysicianUpdate is the builder for updating Physician entities.
type PhysicianUpdate struct {
	config
	hooks      []Hook
	mutation   *PhysicianMutation
	predicates []predicate.Physician
}

// Where adds a new predicate for the builder.
func (pu *PhysicianUpdate) Where(ps ...predicate.Physician) *PhysicianUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetNAME sets the NAME field.
func (pu *PhysicianUpdate) SetNAME(s string) *PhysicianUpdate {
	pu.mutation.SetNAME(s)
	return pu
}

// SetEMAIL sets the EMAIL field.
func (pu *PhysicianUpdate) SetEMAIL(s string) *PhysicianUpdate {
	pu.mutation.SetEMAIL(s)
	return pu
}

// SetFormuserID sets the formuser edge to Positionassingment by id.
func (pu *PhysicianUpdate) SetFormuserID(id int) *PhysicianUpdate {
	pu.mutation.SetFormuserID(id)
	return pu
}

// SetNillableFormuserID sets the formuser edge to Positionassingment by id if the given value is not nil.
func (pu *PhysicianUpdate) SetNillableFormuserID(id *int) *PhysicianUpdate {
	if id != nil {
		pu = pu.SetFormuserID(*id)
	}
	return pu
}

// SetFormuser sets the formuser edge to Positionassingment.
func (pu *PhysicianUpdate) SetFormuser(p *Positionassingment) *PhysicianUpdate {
	return pu.SetFormuserID(p.ID)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pu *PhysicianUpdate) Mutation() *PhysicianMutation {
	return pu.mutation
}

// ClearFormuser clears the formuser edge to Positionassingment.
func (pu *PhysicianUpdate) ClearFormuser() *PhysicianUpdate {
	pu.mutation.ClearFormuser()
	return pu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PhysicianUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PhysicianUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PhysicianUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PhysicianUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PhysicianUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldNAME,
		})
	}
	if value, ok := pu.mutation.EMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldEMAIL,
		})
	}
	if pu.mutation.FormuserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   physician.FormuserTable,
			Columns: []string{physician.FormuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: positionassingment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.FormuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   physician.FormuserTable,
			Columns: []string{physician.FormuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: positionassingment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PhysicianUpdateOne is the builder for updating a single Physician entity.
type PhysicianUpdateOne struct {
	config
	hooks    []Hook
	mutation *PhysicianMutation
}

// SetNAME sets the NAME field.
func (puo *PhysicianUpdateOne) SetNAME(s string) *PhysicianUpdateOne {
	puo.mutation.SetNAME(s)
	return puo
}

// SetEMAIL sets the EMAIL field.
func (puo *PhysicianUpdateOne) SetEMAIL(s string) *PhysicianUpdateOne {
	puo.mutation.SetEMAIL(s)
	return puo
}

// SetFormuserID sets the formuser edge to Positionassingment by id.
func (puo *PhysicianUpdateOne) SetFormuserID(id int) *PhysicianUpdateOne {
	puo.mutation.SetFormuserID(id)
	return puo
}

// SetNillableFormuserID sets the formuser edge to Positionassingment by id if the given value is not nil.
func (puo *PhysicianUpdateOne) SetNillableFormuserID(id *int) *PhysicianUpdateOne {
	if id != nil {
		puo = puo.SetFormuserID(*id)
	}
	return puo
}

// SetFormuser sets the formuser edge to Positionassingment.
func (puo *PhysicianUpdateOne) SetFormuser(p *Positionassingment) *PhysicianUpdateOne {
	return puo.SetFormuserID(p.ID)
}

// Mutation returns the PhysicianMutation object of the builder.
func (puo *PhysicianUpdateOne) Mutation() *PhysicianMutation {
	return puo.mutation
}

// ClearFormuser clears the formuser edge to Positionassingment.
func (puo *PhysicianUpdateOne) ClearFormuser() *PhysicianUpdateOne {
	puo.mutation.ClearFormuser()
	return puo
}

// Save executes the query and returns the updated entity.
func (puo *PhysicianUpdateOne) Save(ctx context.Context) (*Physician, error) {

	var (
		err  error
		node *Physician
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PhysicianUpdateOne) SaveX(ctx context.Context) *Physician {
	ph, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ph
}

// Exec executes the query on the entity.
func (puo *PhysicianUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PhysicianUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PhysicianUpdateOne) sqlSave(ctx context.Context) (ph *Physician, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Physician.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldNAME,
		})
	}
	if value, ok := puo.mutation.EMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldEMAIL,
		})
	}
	if puo.mutation.FormuserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   physician.FormuserTable,
			Columns: []string{physician.FormuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: positionassingment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.FormuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   physician.FormuserTable,
			Columns: []string{physician.FormuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: positionassingment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ph = &Physician{config: puo.config}
	_spec.Assign = ph.assignValues
	_spec.ScanValues = ph.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ph, nil
}
