// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/konrawitAEK/app/ent/physician"
	"github.com/konrawitAEK/app/ent/positionassingment"
)

// PhysicianCreate is the builder for creating a Physician entity.
type PhysicianCreate struct {
	config
	mutation *PhysicianMutation
	hooks    []Hook
}

// SetNAME sets the NAME field.
func (pc *PhysicianCreate) SetNAME(s string) *PhysicianCreate {
	pc.mutation.SetNAME(s)
	return pc
}

// SetEMAIL sets the EMAIL field.
func (pc *PhysicianCreate) SetEMAIL(s string) *PhysicianCreate {
	pc.mutation.SetEMAIL(s)
	return pc
}

// AddFormuserIDs adds the formuser edge to Positionassingment by ids.
func (pc *PhysicianCreate) AddFormuserIDs(ids ...int) *PhysicianCreate {
	pc.mutation.AddFormuserIDs(ids...)
	return pc
}

// AddFormuser adds the formuser edges to Positionassingment.
func (pc *PhysicianCreate) AddFormuser(p ...*Positionassingment) *PhysicianCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddFormuserIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pc *PhysicianCreate) Mutation() *PhysicianMutation {
	return pc.mutation
}

// Save creates the Physician in the database.
func (pc *PhysicianCreate) Save(ctx context.Context) (*Physician, error) {
	if _, ok := pc.mutation.NAME(); !ok {
		return nil, &ValidationError{Name: "NAME", err: errors.New("ent: missing required field \"NAME\"")}
	}
	if _, ok := pc.mutation.EMAIL(); !ok {
		return nil, &ValidationError{Name: "EMAIL", err: errors.New("ent: missing required field \"EMAIL\"")}
	}
	var (
		err  error
		node *Physician
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PhysicianCreate) SaveX(ctx context.Context) *Physician {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PhysicianCreate) sqlSave(ctx context.Context) (*Physician, error) {
	ph, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ph.ID = int(id)
	return ph, nil
}

func (pc *PhysicianCreate) createSpec() (*Physician, *sqlgraph.CreateSpec) {
	var (
		ph    = &Physician{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: physician.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.NAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldNAME,
		})
		ph.NAME = value
	}
	if value, ok := pc.mutation.EMAIL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldEMAIL,
		})
		ph.EMAIL = value
	}
	if nodes := pc.mutation.FormuserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.FormuserTable,
			Columns: []string{physician.FormuserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: positionassingment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return ph, _spec
}
