// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/konrawitAEK/app/ent/physician"
	"github.com/konrawitAEK/app/ent/positionassingment"
)

// Physician is the model entity for the Physician schema.
type Physician struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NAME holds the value of the "NAME" field.
	NAME string `json:"NAME,omitempty"`
	// EMAIL holds the value of the "EMAIL" field.
	EMAIL string `json:"EMAIL,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PhysicianQuery when eager-loading is set.
	Edges PhysicianEdges `json:"edges"`
}

// PhysicianEdges holds the relations/edges for other nodes in the graph.
type PhysicianEdges struct {
	// Formuser holds the value of the formuser edge.
	Formuser *Positionassingment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FormuserOrErr returns the Formuser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhysicianEdges) FormuserOrErr() (*Positionassingment, error) {
	if e.loadedTypes[0] {
		if e.Formuser == nil {
			// The edge formuser was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: positionassingment.Label}
		}
		return e.Formuser, nil
	}
	return nil, &NotLoadedError{edge: "formuser"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Physician) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // NAME
		&sql.NullString{}, // EMAIL
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Physician fields.
func (ph *Physician) assignValues(values ...interface{}) error {
	if m, n := len(values), len(physician.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ph.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field NAME", values[0])
	} else if value.Valid {
		ph.NAME = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field EMAIL", values[1])
	} else if value.Valid {
		ph.EMAIL = value.String
	}
	return nil
}

// QueryFormuser queries the formuser edge of the Physician.
func (ph *Physician) QueryFormuser() *PositionassingmentQuery {
	return (&PhysicianClient{config: ph.config}).QueryFormuser(ph)
}

// Update returns a builder for updating this Physician.
// Note that, you need to call Physician.Unwrap() before calling this method, if this Physician
// was returned from a transaction, and the transaction was committed or rolled back.
func (ph *Physician) Update() *PhysicianUpdateOne {
	return (&PhysicianClient{config: ph.config}).UpdateOne(ph)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ph *Physician) Unwrap() *Physician {
	tx, ok := ph.config.driver.(*txDriver)
	if !ok {
		panic("ent: Physician is not a transactional entity")
	}
	ph.config.driver = tx.drv
	return ph
}

// String implements the fmt.Stringer.
func (ph *Physician) String() string {
	var builder strings.Builder
	builder.WriteString("Physician(")
	builder.WriteString(fmt.Sprintf("id=%v", ph.ID))
	builder.WriteString(", NAME=")
	builder.WriteString(ph.NAME)
	builder.WriteString(", EMAIL=")
	builder.WriteString(ph.EMAIL)
	builder.WriteByte(')')
	return builder.String()
}

// Physicians is a parsable slice of Physician.
type Physicians []*Physician

func (ph Physicians) config(cfg config) {
	for _i := range ph {
		ph[_i].config = cfg
	}
}
