// Code generated by entc, DO NOT EDIT.

package physician

const (
	// Label holds the string label denoting the physician type in the database.
	Label = "physician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNAME holds the string denoting the name field in the database.
	FieldNAME = "name"
	// FieldEMAIL holds the string denoting the email field in the database.
	FieldEMAIL = "email"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the physician in the database.
	Table = "physicians"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "positionassingments"
	// UserInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	UserInverseTable = "positionassingments"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "physician_user"
)

// Columns holds all SQL columns for physician fields.
var Columns = []string{
	FieldID,
	FieldNAME,
	FieldEMAIL,
}
