// Code generated by entc, DO NOT EDIT.

package physician

const (
	// Label holds the string label denoting the physician type in the database.
	Label = "physician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNAME holds the string denoting the name field in the database.
	FieldNAME = "name"
	// FieldEMAIL holds the string denoting the email field in the database.
	FieldEMAIL = "email"

	// EdgeFormuser holds the string denoting the formuser edge name in mutations.
	EdgeFormuser = "formuser"

	// Table holds the table name of the physician in the database.
	Table = "physicians"
	// FormuserTable is the table the holds the formuser relation/edge.
	FormuserTable = "positionassingments"
	// FormuserInverseTable is the table name for the Positionassingment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassingment" package.
	FormuserInverseTable = "positionassingments"
	// FormuserColumn is the table column denoting the formuser relation/edge.
	FormuserColumn = "physician_formuser"
)

// Columns holds all SQL columns for physician fields.
var Columns = []string{
	FieldID,
	FieldNAME,
	FieldEMAIL,
}
