/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPositionassingment,
    EntPositionassingmentFromJSON,
    EntPositionassingmentFromJSONTyped,
    EntPositionassingmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPhysicianEdges
 */
export interface EntPhysicianEdges {
    /**
     * 
     * @type {EntPositionassingment}
     * @memberof EntPhysicianEdges
     */
    user?: EntPositionassingment;
}

export function EntPhysicianEdgesFromJSON(json: any): EntPhysicianEdges {
    return EntPhysicianEdgesFromJSONTyped(json, false);
}

export function EntPhysicianEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPhysicianEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : EntPositionassingmentFromJSON(json['user']),
    };
}

export function EntPhysicianEdgesToJSON(value?: EntPhysicianEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': EntPositionassingmentToJSON(value.user),
    };
}


