/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPositionassingment,
    EntPositionassingmentFromJSON,
    EntPositionassingmentFromJSONTyped,
    EntPositionassingmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPositionEdges
 */
export interface EntPositionEdges {
    /**
     * Formposition holds the value of the formposition edge.
     * @type {Array<EntPositionassingment>}
     * @memberof EntPositionEdges
     */
    formposition?: Array<EntPositionassingment>;
}

export function EntPositionEdgesFromJSON(json: any): EntPositionEdges {
    return EntPositionEdgesFromJSONTyped(json, false);
}

export function EntPositionEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPositionEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formposition': !exists(json, 'formposition') ? undefined : ((json['formposition'] as Array<any>).map(EntPositionassingmentFromJSON)),
    };
}

export function EntPositionEdgesToJSON(value?: EntPositionEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formposition': value.formposition === undefined ? undefined : ((value.formposition as Array<any>).map(EntPositionassingmentToJSON)),
    };
}


