/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPositionassingmentEdges,
    EntPositionassingmentEdgesFromJSON,
    EntPositionassingmentEdgesFromJSONTyped,
    EntPositionassingmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPositionassingment
 */
export interface EntPositionassingment {
    /**
     * DayStart holds the value of the "DayStart" field.
     * @type {string}
     * @memberof EntPositionassingment
     */
    dayStart?: string;
    /**
     * 
     * @type {EntPositionassingmentEdges}
     * @memberof EntPositionassingment
     */
    edges?: EntPositionassingmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPositionassingment
     */
    id?: number;
}

export function EntPositionassingmentFromJSON(json: any): EntPositionassingment {
    return EntPositionassingmentFromJSONTyped(json, false);
}

export function EntPositionassingmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPositionassingment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dayStart': !exists(json, 'DayStart') ? undefined : json['DayStart'],
        'edges': !exists(json, 'edges') ? undefined : EntPositionassingmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPositionassingmentToJSON(value?: EntPositionassingment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DayStart': value.dayStart,
        'edges': EntPositionassingmentEdgesToJSON(value.edges),
        'id': value.id,
    };
}


