/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDepartment,
    EntDepartmentFromJSON,
    EntDepartmentFromJSONTyped,
    EntDepartmentToJSON,
    EntPhysician,
    EntPhysicianFromJSON,
    EntPhysicianFromJSONTyped,
    EntPhysicianToJSON,
    EntPosition,
    EntPositionFromJSON,
    EntPositionFromJSONTyped,
    EntPositionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPositionassingmentEdges
 */
export interface EntPositionassingmentEdges {
    /**
     * 
     * @type {EntPhysician}
     * @memberof EntPositionassingmentEdges
     */
    formdata?: EntPhysician;
    /**
     * 
     * @type {EntDepartment}
     * @memberof EntPositionassingmentEdges
     */
    formdepartment?: EntDepartment;
    /**
     * 
     * @type {EntPosition}
     * @memberof EntPositionassingmentEdges
     */
    formposition?: EntPosition;
}

export function EntPositionassingmentEdgesFromJSON(json: any): EntPositionassingmentEdges {
    return EntPositionassingmentEdgesFromJSONTyped(json, false);
}

export function EntPositionassingmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPositionassingmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formdata': !exists(json, 'formdata') ? undefined : EntPhysicianFromJSON(json['formdata']),
        'formdepartment': !exists(json, 'formdepartment') ? undefined : EntDepartmentFromJSON(json['formdepartment']),
        'formposition': !exists(json, 'formposition') ? undefined : EntPositionFromJSON(json['formposition']),
    };
}

export function EntPositionassingmentEdgesToJSON(value?: EntPositionassingmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formdata': EntPhysicianToJSON(value.formdata),
        'formdepartment': EntDepartmentToJSON(value.formdepartment),
        'formposition': EntPositionToJSON(value.formposition),
    };
}


